table 'Metric Glossary'
	lineageTag: 7a6fa9dc-56c6-4955-ba38-99a15e42b939

	column Page
		dataType: string
		lineageTag: 371f32a7-311c-42f8-a6ac-55ea911a988d
		summarizeBy: none
		sourceColumn: Page

	column Metric
		dataType: string
		lineageTag: e390a11d-33d8-45d3-82f5-561723b0b656
		summarizeBy: none
		sourceColumn: Metric

	column Description
		dataType: string
		lineageTag: 01509042-77cb-4fea-8381-0f86f311b0a9
		summarizeBy: none
		sourceColumn: Description

	column DataStatus
		dataType: string
		lineageTag: 9b698593-2cc7-41d4-b156-bc7b72c4e343
		summarizeBy: none
		sourceColumn: DataStatus

	column PageOrder
		dataType: int64
		lineageTag: 68628de8-a773-41e3-ba0b-a4fbd2c9757d
		summarizeBy: none
		sourceColumn: PageOrder

	column MetricOrder
		dataType: int64
		lineageTag: 26e74550-a41f-451d-9a0a-dece76d1093f
		summarizeBy: none
		sourceColumn: MetricOrder

	column PageDescription
		dataType: string
		lineageTag: 841c84ef-afbb-42cb-92f5-1e1bbf57f0d9
		summarizeBy: none
		sourceColumn: PageDescription

	column SortKey
		dataType: int64
		formatString: ;;;
		lineageTag: 9c6d2b3a-8e14-4f0a-b6c7-2d1e5a7f9c3b
		summarizeBy: none
		sourceColumn: SortKey

	partition 'Metric Glossary' = m
		mode: import
		source =
				let
					Seed = #table(
						type table [Page = text, Metric = text, Description = text, DataStatus = text, PageOrder = Int64.Type, MetricOrder = Int64.Type, PageDescription = text],
						{
							{"🧭 Start Here", "Purpose", "Navigation hub for moving from executive adoption status to weekly trends, organizational patterns, user maturity, champions, observed work patterns, and activity evidence.", "Reference", 0, 1, "How to navigate the report and interpret source coverage."},
							{"🧭 Start Here", "Observed data source", "Cowork activity is measured from customer Purview and Copilot audit-log records filtered to the Cowork workload. No sample activity is substituted.", "Observed", 0, 2, "How to navigate the report and interpret source coverage."},
							{"🧭 Start Here", "Data period", "The connected audit-log date range. Weekly visuals align dates to Monday-starting weeks and automatically use the latest week with observed Cowork activity.", "Observed", 0, 3, "How to navigate the report and interpret source coverage."},
							{"🧭 Start Here", "Data Status", "Observed comes directly from source records; Derived is calculated from observed fields; Modeled uses declared assumptions; Allocated estimate distributes a modeled total; Unavailable means required evidence is missing. Convention marks a template-defined rule, Reference explains a definition, and Optional input requires a separate customer export.", "Reference", 0, 4, "How to navigate the report and interpret source coverage."},
							{"🧭 Start Here", "Filters by page", "Filter availability varies by page and can be inline or behind More filters. Each page section in this guide documents its scope. Start Here is navigation-only, Momentum Score Guide explains and optionally tunes the index, and the Adoption Metric Guide uses its Section filter.", "Reference", 0, 5, "How to navigate the report and interpret source coverage."},
							{"🧭 Start Here", "Calendar date filter", "Where present, the Between slicer on Dim_Date[Date] filters selected calendar dates rather than selecting a whole year.", "Observed", 0, 6, "How to navigate the report and interpret source coverage."},
							{"🧭 Start Here", "LLM / model filter", "Where present, filters Cowork activity by observed Purview ModelProviderName. It can show not available when the tenant export omits model attribution.", "Optional input", 0, 7, "How to navigate the report and interpret source coverage."},
							{"🧭 Start Here", "Scheduled-data readiness", "Reports whether the optional Microsoft admin center usage export is connected and whether scheduled tasks are available for the Automating rung.", "Optional input", 0, 8, "How to navigate the report and interpret source coverage."},
							{"Executive Summary", "Adoption momentum index (0–100)", "A latest-week composite whose defaults are 35% weekly return rate, 25% active-day consistency capped at 3 days, 25% prompt intensity capped at 12 prompts per user, and 15% share of active users on delegation rung 3 or 4. Weights and caps are adjustable on Momentum Score Guide. The index returns blank when weights do not total 100%, and a customer-tuned index is not comparable across tenants.", "Convention", 1, 1, "Latest-week adoption reach, consistency, intensity, and maturity."},
							{"Executive Summary", "Weekly active users", "Distinct users with at least one observed Cowork activity in the latest active week. In weekly charts and tables, it evaluates separately for each week.", "Observed", 1, 2, "Latest-week adoption reach, consistency, intensity, and maturity."},
							{"Executive Summary", "Weekly tasks", "Distinct observed Cowork conversation threads in the latest active week.", "Observed", 1, 3, "Latest-week adoption reach, consistency, intensity, and maturity."},
							{"Executive Summary", "Prompts per active user", "Observed Cowork prompt count divided by weekly active users, evaluated at the latest active week on cards and per week on trends.", "Derived", 1, 4, "Latest-week adoption reach, consistency, intensity, and maturity."},
							{"Executive Summary", "Active days per user", "Average number of distinct days each active user used Cowork during a week.", "Derived", 1, 5, "Latest-week adoption reach, consistency, intensity, and maturity."},
							{"Executive Summary", "Weekly return rate", "Share of users active in the prior week who were also active in the current week.", "Derived", 1, 6, "Latest-week adoption reach, consistency, intensity, and maturity."},
							{"Weekly Adoption & Usage", "Usage overview bookmark", "ESS-inspired view combining weekly Cowork tasks, previous-week task volume, weekly active users, and ranked department and country usage.", "Derived", 2, 1, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Weekly Adoption & Usage", "Previous week", "Cowork task volume from the week immediately before each displayed week. It is shown as context, not added to current-week tasks.", "Observed", 2, 2, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Weekly Adoption & Usage", "Latest 12 active weeks", "The rolling display window ending on the latest week that contains observed Cowork activity. Older weeks return blank in these visuals; Calendar date, Department, Country, Value tier, LLM / model, and Copilot License are available behind More filters.", "Derived", 2, 3, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Weekly Adoption & Usage", "Metric bookmarks", "Usage overview, weekly active users, adoption momentum index (0–100), prompts per user, active days, and return rate switch the central view without clearing Calendar date, Department, Country, Value tier, LLM / model, or Copilot License filters.", "Reference", 2, 4, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Weekly Adoption & Usage", "Heatmap color", "Color is a relative intensity cue within the current filtered visual. Darker cells mean higher values; always read the number for precision.", "Reference", 2, 5, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Adoption by Attributes", "Cowork tasks by attribute", "Distinct observed Cowork task threads grouped by Department or Country in the current filter context.", "Observed", 3, 1, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption by Attributes", "Department and country", "Organizational attributes supplied by the optional customer Entra or HR export. Breakdowns remain unavailable when matching enrichment is not connected.", "Optional input", 3, 2, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption by Attributes", "Prompt-volume tier by department", "Rolling 12-week Power, Habitual, Novice, Low, Inactive, and Insufficient sample classifications summarized by department.", "Convention", 3, 3, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption by Attributes", "Delegation ladder by department", "Not started, Trying, Using, Delegating, and Automating classifications summarized by department using the same ladder as User Maturity.", "Convention", 3, 4, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption by Attributes", "Page filters", "Calendar date, Department, Country, Copilot License, and LLM / model scope both task totals and tier distributions. Organization-dependent visuals require matching enrichment.", "Reference", 3, 5, "Where adoption and maturity patterns differ across organizational attributes."},
							{"User Maturity", "Delegation ladder index", "Average position of active users across Trying, Using, Delegating, and Automating, scaled to 0-100.", "Derived", 4, 1, "How deeply users delegate work and how consistently they use Cowork."},
							{"User Maturity", "Multi-skill task %", "Share of observed Cowork threads that invoke more than one skill or tool.", "Observed", 4, 2, "How deeply users delegate work and how consistently they use Cowork."},
							{"User Maturity", "Average task duration", "Average elapsed minutes from the first to last observed record in a Cowork thread.", "Observed", 4, 3, "How deeply users delegate work and how consistently they use Cowork."},
							{"User Maturity", "Average skills per task", "Observed skill invocations divided by distinct Cowork threads.", "Derived", 4, 4, "How deeply users delegate work and how consistently they use Cowork."},
							{"User Maturity", "Cowork prompt-volume tier", "Rolling 12-week tiers ranked within the selected tenant population: Power is the top 10% by prompt volume and active in at least 9 of 12 weeks; Habitual is the top 40% and active in at least 9 weeks; Novice is the top 80%; Low is below that; Inactive has no prompts. At least 20 active users are required; smaller populations return Insufficient sample.", "Convention", 4, 5, "How deeply users delegate work and how consistently they use Cowork."},
							{"User Maturity", "Delegation ladder", "One customer-facing ladder is used throughout the report: Not started has no observed tasks; Trying is shorter single-skill work; Using has average task duration of at least 5 minutes; Delegating has at least 30% multi-skill tasks; Automating has any lifetime scheduled-task total. The 5-minute and 30% thresholds are template conventions to revisit with tenant evidence.", "Convention", 4, 6, "How deeply users delegate work and how consistently they use Cowork."},
							{"User Maturity", "Power users %", "Power users divided by everyone classified in the rolling 12-week Cowork prompt-volume tier, including the Insufficient sample state when the active population is below 20. Treat it as an enablement signal, not a performance rating.", "Derived", 4, 7, "How deeply users delegate work and how consistently they use Cowork."},
							{"User Maturity", "Scheduled share %", "Share of per-user lifetime Cowork tasks reported as scheduled rather than user-initiated. It requires the optional Microsoft admin center usage export and does not vary with the date filter.", "Optional input", 4, 8, "How deeply users delegate work and how consistently they use Cowork."},
							{"User Maturity", "Scheduled-task data grain", "The Automating rung is lifetime-scoped because the admin center export supplies per-user lifetime scheduled-task totals without dates. Not started, Trying, Using, and Delegating are period-scoped and respond to the date filter.", "Optional input", 4, 9, "How deeply users delegate work and how consistently they use Cowork."},
							{"Cowork Champions", "Potential champions", "Users who meet the minimum evidence floor and rank within the selected Top 5%, Top 10%, or Top 20% of the eligible population. Date and category filters recalculate evidence; organization filters narrow the displayed list.", "Derived", 5, 1, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Eligibility floor", "At least three observed Cowork task threads across at least two active weeks in the current date and category context.", "Reference", 5, 2, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Champion evidence score", "A transparent 0-100 score: 40% category-task activity percentile, 35% active-week consistency percentile, and 25% normalized delegation maturity.", "Derived", 5, 3, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Activity percentile", "The user's observed Cowork task-thread volume ranked against other eligible users in the current date and category context.", "Derived", 5, 4, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Consistency percentile", "The user's distinct active-week count ranked against other eligible users in the current date and category context.", "Derived", 5, 5, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Delegation maturity component", "The existing Trying, Using, Delegating, or Automating rung normalized to a 0-100 component of the champion evidence score.", "Derived", 5, 6, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Champion Tier", "Selects exactly the top 5%, 10%, or 20% of eligible users after deterministic tie-breaking. The default is Top 10%.", "Reference", 5, 7, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Category lens", "A visible multi-select filter over observed task categories. Selecting a category recalculates candidate evidence and department coverage; clearing it returns to all categories.", "Observed", 5, 8, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Department coverage", "Departments with at least one potential champion divided by departments with eligible users. This measure requires matching optional organization enrichment.", "Optional input", 5, 9, "Potential enablement champions and coverage gaps by category and department."},
							{"Cowork Champions", "Interpretation boundary", "Potential champions are engagement signals for enablement planning, not employee-performance ratings. Confirm role fit, willingness, and manager support before outreach.", "Reference", 5, 10, "Potential enablement champions and coverage gaps by category and department."},
							{"Activity & Assisted Hours", "Observed activity records", "Count of observed Cowork audit-log records in the current filter context.", "Observed", 6, 1, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Activity & Assisted Hours", "Active users", "Distinct users represented in the observed activity records.", "Observed", 6, 2, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Activity & Assisted Hours", "Activity records per user", "Observed activity records divided by distinct active users.", "Derived", 6, 3, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Activity & Assisted Hours", "Estimated hours saved", "Modeled assisted hours calculated from observed task activity and declared category time assumptions. It is not elapsed time measured from a time study.", "Modeled", 6, 4, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Activity & Assisted Hours", "Observed activity by action count", "Observed Cowork action records grouped by mapped work category. A distinct Cowork thread can produce more than one action record, so this count can exceed distinct task threads. Unmapped actions remain visible for taxonomy maintenance.", "Observed", 6, 5, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Activity & Assisted Hours", "Cowork actions by category and department", "The same observed action-record count split by mapped work category and matched user department. Total bar length shows department volume; colored segments show work mix. Department grouping requires the optional customer organization export.", "Optional input", 6, 6, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Activity & Assisted Hours", "Page filters", "Calendar date, Department, Country, Manager, Job family, and Copilot License scope the activity and assisted-hours calculations.", "Reference", 6, 7, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"What They Use It For", "Actions by Category", "Observed Cowork skill invocations grouped into the report's task categories and action value tiers.", "Observed", 7, 1, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Action value tier", "High, Mid, or Low grouping of task categories based on the declared midpoint of the cited time-saved range. It is a category attribute, not a user performance score.", "Reference", 7, 2, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Observed activities", "Count of measured Cowork skill or tool invocations. Reference action examples are not counted unless they appear in the audit data.", "Observed", 7, 3, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Skill mapping coverage", "Share of observed Cowork skills or tools mapped to a known task category; unmapped items stay visible for taxonomy maintenance.", "Observed", 7, 4, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Usage Explorer", "Two-view bookmark sequence for Action explorer and User details. Both preserve the current filter selections.", "Reference", 7, 5, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Page filters", "Calendar date, Department, Country, Copilot License, LLM / model, action value tier, and task category scope the action and user-detail views.", "Reference", 7, 6, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Consumption data availability", "Confirms that a customer-provided Microsoft 365 admin center Cowork consumption export loaded and matched at least one detected Cowork user. Credit and session metrics remain blank when this optional evidence is unavailable.", "Optional input", 7, 7, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Total credits used", "Sum of Monthly credits used from the matched Cowork consumption export in the current filter context.", "Optional input", 7, 8, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Total credit limit", "Sum of Monthly credit limit from the matched Cowork consumption export in the current filter context.", "Optional input", 7, 9, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Credits remaining", "Total credit limit minus total credits used. A negative result means observed use exceeded the allocated monthly limit.", "Derived", 7, 10, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Utilization %", "Total credits used divided by total credit limit in the current filter context. It can exceed 100% when use is above the allocated limit.", "Derived", 7, 11, "What users ask Cowork to do and how those actions are grouped."},
							{"What They Use It For", "Total sessions", "Sum of Session Count from the matched Cowork consumption export in the current filter context.", "Optional input", 7, 12, "What users ask Cowork to do and how those actions are grouped."},
							{"Momentum Score Guide", "Current momentum score", "The latest active week's 0–100 composite. Read it as a directional adoption signal, not a performance grade.", "Derived", 8, 1, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Momentum Score Guide", "Return signal", "Weekly return rate: the share of prior-week users who were also active in the current week. Default weight: 35%.", "Derived", 8, 2, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Momentum Score Guide", "Consistency signal", "Average active days per user divided by the selected active-day cap, limited to 100%. Default weight: 25%; default full-credit cap: 3 days per week.", "Convention", 8, 3, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Momentum Score Guide", "Intensity signal", "Prompts per active user divided by the selected prompt cap, limited to 100%. Default weight: 25%; default full-credit cap: 12 prompts per user per week.", "Convention", 8, 4, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Momentum Score Guide", "Maturity signal", "Share of active users classified as Delegating or Automating. Default weight: 15%.", "Derived", 8, 5, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Momentum Score Guide", "Default weights", "Return 35%, consistency 25%, intensity 25%, and maturity 15%. The four selected weights must total 100%.", "Convention", 8, 6, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Momentum Score Guide", "Normalization caps", "Caps set the point where consistency or intensity earns full component credit. Activity above a cap adds no further points to that component.", "Convention", 8, 7, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Momentum Score Guide", "Weight guard", "If selected weights do not total 100% within the model tolerance, the adoption momentum index returns blank and Momentum Weight Status explains the issue.", "Convention", 8, 8, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Momentum Score Guide", "Comparability", "Changing weights or caps creates a customer-tuned index that should be compared only over time under the same settings, not across organizations with different settings.", "Reference", 8, 9, "Plain-language explanation and optional controls for the adoption momentum index."},
							{"Adoption Metric Guide", "Section filter", "Lists the ten report page display names in report order and filters the guide to definitions for the selected page.", "Reference", 9, 1, "Definitions and data-status guidance for every report page."},
							{"Adoption Metric Guide", "Sort order", "Rows sort by page order and then metric order through SortKey = PageOrder × 100 + MetricOrder.", "Reference", 9, 2, "Definitions and data-status guidance for every report page."},
							{"Adoption Metric Guide", "Interpretation boundary", "Read Data Status before interpreting a metric, and use trends plus local context rather than a single score for enablement or governance decisions.", "Reference", 9, 3, "Definitions and data-status guidance for every report page."}
						}
					),
					Final = Table.AddColumn(Seed, "SortKey", each [PageOrder] * 100 + [MetricOrder], Int64.Type)
				in
					Final

	annotation PBI_ResultType = Table
