table 'Metric Glossary'
	lineageTag: 7a6fa9dc-56c6-4955-ba38-99a15e42b939

	column Page
		dataType: string
		lineageTag: 371f32a7-311c-42f8-a6ac-55ea911a988d
		summarizeBy: none
		sourceColumn: Page

	column Metric
		dataType: string
		lineageTag: e390a11d-33d8-45d3-82f5-561723b0b656
		summarizeBy: none
		sourceColumn: Metric

	column Description
		dataType: string
		lineageTag: 01509042-77cb-4fea-8381-0f86f311b0a9
		summarizeBy: none
		sourceColumn: Description

	column DataStatus
		dataType: string
		lineageTag: 9b698593-2cc7-41d4-b156-bc7b72c4e343
		summarizeBy: none
		sourceColumn: DataStatus

	column PageOrder
		dataType: int64
		lineageTag: 68628de8-a773-41e3-ba0b-a4fbd2c9757d
		summarizeBy: none
		sourceColumn: PageOrder

	column MetricOrder
		dataType: int64
		lineageTag: 26e74550-a41f-451d-9a0a-dece76d1093f
		summarizeBy: none
		sourceColumn: MetricOrder

	column PageDescription
		dataType: string
		lineageTag: 841c84ef-afbb-42cb-92f5-1e1bbf57f0d9
		summarizeBy: none
		sourceColumn: PageDescription

	column SortKey
		dataType: int64
		formatString: ;;;
		lineageTag: 9c6d2b3a-8e14-4f0a-b6c7-2d1e5a7f9c3b
		summarizeBy: none
		sourceColumn: SortKey

	partition 'Metric Glossary' = m
		mode: import
		source =
				let
					Seed = #table(
						type table [Page = text, Metric = text, Description = text, DataStatus = text, PageOrder = Int64.Type, MetricOrder = Int64.Type, PageDescription = text],
						{
							{"Cowork Adoption Scorecard", "Purpose", "Start with adoption health, then move to weekly trends, organizational gaps, scalable work patterns, or potential enablement partners.", "Reference", 0, 1, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Observed data source", "Cowork activity is measured from customer Purview and Copilot audit-log records filtered to the Cowork workload. No sample activity is substituted.", "Observed", 0, 2, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Data period", "The connected audit-log date range. Weekly visuals align dates to Monday-starting weeks and automatically use the latest week with observed Cowork activity.", "Observed", 0, 3, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Data Status", "Observed comes directly from source records; Derived is calculated from observed fields; Modeled uses declared assumptions; Allocated estimate distributes a modeled total; Unavailable means required evidence is missing. Convention marks a template-defined rule, Reference explains a definition, and Optional input requires a separate customer export.", "Reference", 0, 4, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Filters by page", "Filter availability varies by page and can be inline or behind More filters. Capacity Assumptions controls only the modeled Capacity hours and Labor-capacity scenario shown on Demand & Capacity Scenario.", "Reference", 0, 5, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Calendar date filter", "Where present, the Between slicer on Dim_Date[Date] filters selected calendar dates rather than selecting a whole year.", "Observed", 0, 6, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "LLM / model filter", "Where present, filters Cowork activity by observed Purview ModelProviderName. It can show not available when the tenant export omits model attribution.", "Optional input", 0, 7, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Scheduled-data readiness", "Reports whether the optional Microsoft admin center usage export is connected and whether scheduled tasks are available for the Automating rung.", "Optional input", 0, 8, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Power users %", "Share of users classified in the rolling 12-week Power tier: the top 10% by prompt volume who were active in at least 9 of 12 weeks. At least 20 active users are required for tiering.", "Derived", 0, 9, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Weekly active users", "Distinct users with at least one observed Cowork activity in the latest active week. In weekly charts and tables, it evaluates separately for each week.", "Observed", 0, 10, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Weekly tasks", "Distinct observed Cowork conversation threads in the latest active week.", "Observed", 0, 11, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Prompts per active user", "Observed Cowork prompt count divided by weekly active users, evaluated at the latest active week on cards and per week on trends.", "Derived", 0, 12, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Active days per user", "Average number of distinct days each active user used Cowork during a week.", "Derived", 0, 13, "Start here for adoption health, decision routes, and source coverage."},
							{"Cowork Adoption Scorecard", "Weekly return rate", "Share of users active in the prior week who were also active in the current week.", "Derived", 0, 14, "Start here for adoption health, decision routes, and source coverage."},
							{"Weekly Adoption & Usage", "Usage overview bookmark", "ESS-inspired view combining weekly Cowork tasks, previous-week task volume, weekly active users, and ranked department and country usage.", "Derived", 2, 1, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Weekly Adoption & Usage", "Previous week", "Cowork task volume from the week immediately before each displayed week. It is shown as context, not added to current-week tasks.", "Observed", 2, 2, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Weekly Adoption & Usage", "Latest 12 active weeks", "The rolling display window ending on the latest week that contains observed Cowork activity. Older weeks return blank in these visuals; Calendar date, Department, Country, Value tier, LLM / model, and Copilot License are available behind More filters.", "Derived", 2, 3, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Weekly Adoption & Usage", "Metric bookmarks", "Usage overview, weekly active users, power users %, prompts per user, active days, and return rate switch the central view without clearing Calendar date, Department, Country, Value tier, LLM / model, or Copilot License filters.", "Reference", 2, 4, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Weekly Adoption & Usage", "Heatmap color", "Color is a relative intensity cue within the current filtered visual. Darker cells mean higher values; always read the number for precision.", "Reference", 2, 5, "Bookmark views for usage concentration and weekly adoption patterns."},
							{"Adoption by Attributes", "Cowork tasks by attribute", "Distinct observed Cowork task threads grouped by Department or Country in the current filter context.", "Observed", 3, 1, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption by Attributes", "Department and country", "Organizational attributes supplied by the optional customer Entra or HR export. Breakdowns remain unavailable when matching enrichment is not connected.", "Optional input", 3, 2, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption by Attributes", "Prompt-volume tier by department", "Rolling 12-week Power, Habitual, Novice, Low, Inactive, and Insufficient sample classifications summarized by department.", "Convention", 3, 3, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption by Attributes", "Delegation ladder by department", "Not started, Trying, Using, Delegating, and Automating classifications summarized by department using the same ladder as Adoption Maturity.", "Convention", 3, 4, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption by Attributes", "Page filters", "Calendar date, Department, Country, Copilot License, and LLM / model scope both task totals and tier distributions. Organization-dependent visuals require matching enrichment.", "Reference", 3, 5, "Where adoption and maturity patterns differ across organizational attributes."},
							{"Adoption Maturity", "Delegation ladder index", "Average position of active users across Trying, Using, Delegating, and Automating, scaled to 0-100.", "Derived", 4, 1, "How deeply users delegate work and how consistently they use Cowork."},
							{"Adoption Maturity", "Multi-skill task %", "Share of observed Cowork threads that invoke more than one skill or tool.", "Observed", 4, 2, "How deeply users delegate work and how consistently they use Cowork."},
							{"Adoption Maturity", "Average observed thread span", "Average elapsed minutes from the first to last observed audit event in a Cowork thread. This is not measured human attention time.", "Observed", 4, 3, "How deeply users delegate work and how consistently they use Cowork."},
							{"Adoption Maturity", "Average skills per task", "Observed skill invocations divided by distinct Cowork threads.", "Derived", 4, 4, "How deeply users delegate work and how consistently they use Cowork."},
							{"Adoption Maturity", "Cowork prompt-volume tier", "Rolling 12-week tiers ranked within the selected tenant population: Power is the top 10% by prompt volume and active in at least 9 of 12 weeks; Habitual is the top 40% and active in at least 9 weeks; Novice is the top 80%; Low is below that; Inactive has no prompts. At least 20 active users are required; smaller populations return Insufficient sample.", "Convention", 4, 5, "How deeply users delegate work and how consistently they use Cowork."},
							{"Adoption Maturity", "Delegation ladder", "One customer-facing ladder is used throughout the report: Not started has no observed tasks; Trying is shorter single-skill work; Using has an average observed thread span of at least 5 minutes; Delegating has at least 30% multi-skill tasks; Automating has any lifetime scheduled-task total. The 5-minute and 30% thresholds are template conventions to revisit with tenant evidence.", "Convention", 4, 6, "How deeply users delegate work and how consistently they use Cowork."},
							{"Adoption Maturity", "Power users %", "Power users divided by everyone classified in the rolling 12-week Cowork prompt-volume tier, including the Insufficient sample state when the active population is below 20. Treat it as an enablement signal, not a performance rating.", "Derived", 4, 7, "How deeply users delegate work and how consistently they use Cowork."},
							{"Adoption Maturity", "Scheduled share %", "Share of per-user lifetime Cowork tasks reported as scheduled rather than user-initiated. It requires the optional Microsoft admin center usage export and does not vary with the date filter.", "Optional input", 4, 8, "How deeply users delegate work and how consistently they use Cowork."},
							{"Adoption Maturity", "Scheduled-task data grain", "The Automating rung is lifetime-scoped because the admin center export supplies per-user lifetime scheduled-task totals without dates. Not started, Trying, Using, and Delegating are period-scoped and respond to the date filter.", "Optional input", 4, 9, "How deeply users delegate work and how consistently they use Cowork."},
							{"Enablement Partners", "Potential champions", "Users who meet the minimum evidence floor and rank within the selected Top 5%, Top 10%, or Top 20% of the eligible population. Date and category filters recalculate evidence; organization filters narrow the displayed list.", "Derived", 5, 1, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Eligibility floor", "At least three observed Cowork task threads across at least two active weeks in the current date and category context.", "Reference", 5, 2, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Champion evidence score", "A transparent 0-100 score: 40% category-task activity percentile, 35% active-week consistency percentile, and 25% normalized delegation maturity.", "Derived", 5, 3, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Activity percentile", "The user's observed Cowork task-thread volume ranked against other eligible users in the current date and category context.", "Derived", 5, 4, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Consistency percentile", "The user's distinct active-week count ranked against other eligible users in the current date and category context.", "Derived", 5, 5, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Delegation maturity component", "The existing Trying, Using, Delegating, or Automating rung normalized to a 0-100 component of the champion evidence score.", "Derived", 5, 6, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Champion Tier", "Selects exactly the top 5%, 10%, or 20% of eligible users after deterministic tie-breaking. The default is Top 10%.", "Reference", 5, 7, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Category lens", "A visible multi-select filter over observed task categories. Selecting a category recalculates candidate evidence and department coverage; clearing it returns to all categories.", "Observed", 5, 8, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Department coverage", "Departments with at least one potential champion divided by departments with eligible users. This measure requires matching optional organization enrichment.", "Optional input", 5, 9, "Potential enablement champions and coverage gaps by category and department."},
							{"Enablement Partners", "Interpretation boundary", "Potential champions are engagement signals for enablement planning, not employee-performance ratings. Confirm role fit, willingness, and manager support before outreach.", "Reference", 5, 10, "Potential enablement champions and coverage gaps by category and department."},
							{"Demand & Capacity Scenario", "Observed activity records", "Count of observed Cowork audit-log records in the current filter context.", "Observed", 6, 1, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Demand & Capacity Scenario", "Active users", "Distinct users represented in the observed activity records.", "Observed", 6, 2, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Demand & Capacity Scenario", "Activity records per user", "Observed activity records divided by distinct active users.", "Derived", 6, 3, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Demand & Capacity Scenario", "Capacity hours", "Modeled capacity hours calculated from observed task activity and the Low, Mid, High, or Custom minutes configured on Capacity Assumptions. It is not elapsed time measured from a time study.", "Modeled", 6, 4, "Observed task demand and modeled capacity scenarios by work category."},
							{"Demand & Capacity Scenario", "Observed activity by action count", "Observed Cowork action records grouped by mapped work category. A distinct Cowork thread can produce more than one action record, so this count can exceed distinct task threads. Unmapped actions remain visible for taxonomy maintenance.", "Observed", 6, 5, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Demand & Capacity Scenario", "Cowork actions by category and department", "The same observed action-record count split by mapped work category and matched user department. Total bar length shows department volume; colored segments show work mix. Department grouping requires the optional customer organization export.", "Optional input", 6, 6, "Observed activity volume and modeled assisted-time estimates by work category."},
							{"Demand & Capacity Scenario", "Capacity Assumptions dependency", "Capacity Assumptions drives Capacity hours and Labor-capacity scenario on this page. It does not change observed tasks, users, active weeks, adoption, maturity, or enablement-partner evidence.", "Reference", 6, 7, "Observed task demand and modeled capacity scenarios by work category."},
							{"Scalable Work Patterns", "Actions by Category", "Observed Cowork skill invocations grouped into the report's task categories and action value tiers.", "Observed", 7, 1, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Action value tier", "High, Mid, or Low grouping of task categories based on the declared midpoint of the cited time-saved range. It is a category attribute, not a user performance score.", "Reference", 7, 2, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Observed activities", "Count of measured Cowork skill or tool invocations. Reference action examples are not counted unless they appear in the audit data.", "Observed", 7, 3, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Skill mapping coverage", "Share of observed Cowork skills or tools mapped to a known task category; unmapped items stay visible for taxonomy maintenance.", "Observed", 7, 4, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Usage Explorer", "Two-view bookmark sequence for Action explorer and User details. Both preserve the current filter selections.", "Reference", 7, 5, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Page filters", "Calendar date, Department, Country, Copilot License, LLM / model, action value tier, and task category scope the action and user-detail views.", "Reference", 7, 6, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Consumption data availability", "Confirms that a customer-provided Microsoft 365 admin center Cowork consumption export loaded and matched at least one detected Cowork user. Credit and session metrics remain blank when this optional evidence is unavailable.", "Optional input", 7, 7, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Total credits used", "Sum of Monthly credits used from the matched Cowork consumption export in the current filter context.", "Optional input", 7, 8, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Total credit limit", "Sum of Monthly credit limit from the matched Cowork consumption export in the current filter context.", "Optional input", 7, 9, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Credits remaining", "Total credit limit minus total credits used. A negative result means observed use exceeded the allocated monthly limit.", "Derived", 7, 10, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Utilization %", "Total credits used divided by total credit limit in the current filter context. It can exceed 100% when use is above the allocated limit.", "Derived", 7, 11, "What users ask Cowork to do and how those actions are grouped."},
							{"Scalable Work Patterns", "Total sessions", "Sum of Session Count from the matched Cowork consumption export in the current filter context.", "Optional input", 7, 12, "What users ask Cowork to do and how those actions are grouped."},
							{"Capacity Assumptions", "Destination page", "These controls drive only Capacity hours and Labor-capacity scenario on Demand & Capacity Scenario.", "Reference", 8, 1, "Configure the modeled outputs shown on Demand & Capacity Scenario."},
							{"Capacity Assumptions", "Estimate basis", "Low, Mid, and High use governed research-based category estimates. Custom activates the eight customer-editable minute controls.", "Reference", 8, 2, "Configure the modeled outputs shown on Demand & Capacity Scenario."},
							{"Capacity Assumptions", "Custom category minutes", "Eight synchronized controls set customer-specific capacity minutes for Analysis & Research, Document & content, Email workflows, Meeting workflows, Communication workflows, Specialized workflows, Write or debug code, and General assistance / Other.", "Modeled", 8, 3, "Configure the modeled outputs shown on Demand & Capacity Scenario."},
							{"Capacity Assumptions", "Capacity-hours calculation", "Observed task count multiplied by selected category minutes and divided by 60. It is a scenario estimate, not measured elapsed time or proven productivity.", "Modeled", 8, 4, "Configure the modeled outputs shown on Demand & Capacity Scenario."},
							{"Capacity Assumptions", "Unaffected metrics", "Observed tasks, users, active weeks, adoption, maturity, and enablement-partner evidence do not change when these assumptions change.", "Reference", 8, 5, "Configure the modeled outputs shown on Demand & Capacity Scenario."},
							{"Capacity Assumptions", "Comparability", "Document customer-edited Custom values before comparison. Results using different category assumptions are not directly comparable.", "Reference", 8, 6, "Configure the modeled outputs shown on Demand & Capacity Scenario."},
							{"Adoption Metric Guide", "Section filter", "Lists the ten report page display names in report order and filters the guide to definitions for the selected page.", "Reference", 9, 1, "Definitions and data-status guidance for every report page."},
							{"Adoption Metric Guide", "Sort order", "Rows sort by page order and then metric order through SortKey = PageOrder × 100 + MetricOrder.", "Reference", 9, 2, "Definitions and data-status guidance for every report page."},
							{"Adoption Metric Guide", "Interpretation boundary", "Read Data Status before interpreting a metric, and use trends plus local context rather than a single score for enablement or governance decisions.", "Reference", 9, 3, "Definitions and data-status guidance for every report page."}
						}
					),
					Final = Table.AddColumn(Seed, "SortKey", each [PageOrder] * 100 + [MetricOrder], Int64.Type)
				in
					Final

	annotation PBI_ResultType = Table
